package com.harry.ebangbang.app_final;

/**
 * Created by Harry on 2018/11/6.
 * 处理RxJava切断管道方法
 * 命名方法 - 类名+方法名
 */
public enum DisposableFinal {

    LOGIN_ACTIVITY_LOGIN,
    REGISTER_ACTIVITY_REGISTER,
    REGISTER_ACTIVITY_GET_VERIFY_CODE,
    REGISTER_ACTIVITY_CHECK_VERIFY_CODE,
    FORGET_PASSWORD_ACTIVITY_FORGET_PASSWORD,
    FORGET_PASSWORD_ACTIVITY_GET_VERIFY_CODE,
    FORGET_PASSWORD_ACTIVITY_CHECK_VERIFY_CODE,
    HOME_FRAGMENT_GET_LIST,
    HOME_FRAGMENT_GET_BANNER,
    HOME_FRAGMENT_CURRENT_POSITION,
    CLASSIFICATION_FRAGMENT_GET_FIRST_LEVEL,
    CLASSIFICATION_FRAGMENT_GET_SECOND_LEVEL,
    SHOPPING_CART_FRAGMENT_GET_SHOPPING_LIST,
    SHOPPING_CART_FRAGMENT_DELETE,
    SHOPPING_CART_FRAGMENT_ADD,
    SHOPPING_CART_FRAGMENT_REDUCE,
    SHOPPING_CART_FRAGMENT_CHECK,
    SUBMIT_ORDER_ACTIVITY_GET_PAGE_DETAIL,
    SUBMIT_ORDER_ACTIVITY_SUBMIT_ORDER,
    ADD_ADDRESS_ACTIVITY_PUT_ADDRESS,
    CHOOSE_COUPON_ACTIVITY_GET_COUPON_LIST,
    PAYMENT_METHOD_ACTIVITY_WX_PAY,
    PAYMENT_METHOD_ACTIVITY_ALI_PAY,
    SEARCH_ACTIVITY_SEARCH,
}
